import type{Card}from'./cards';import{exactEquity,potOdds,cleanOuts}from'./equity';import type{WeightedCombo}from'./ranges';
export type Intent='价值'|'保护'|'半诈唬'|'纯诈唬'|'控池'|'诱导';
export type Alternative={kind:'fold'|'call'|'raise';action:string;amount:number;ev:number;risk:number;intent:Intent;equity:number;foldEquity:number};
export type DecisionFacts={equity:number;requiredEquity:number;outs:{clean:Card[];dirty:Card[]};alternatives:Alternative[];recommended:Alternative;risk:{playersBehind:number;effectiveStack:number;spr:number};assumptions:string[]};
export type DecisionAnalysisInput={hero:Card[];board:Card[];range:WeightedCombo[];pot:number;toCall:number;stack:number;playersBehind:number;seed:number};
export function classifyIntent(equity:number,foldEquity:number,drawPotential:number):Intent{if(equity>.7&&foldEquity>.35)return'价值';if(equity>.7&&foldEquity<.2&&drawPotential<.05)return'诱导';if(equity>.5&&foldEquity<.2)return'控池';if(equity>.5)return'保护';if(drawPotential>.2)return'半诈唬';return'纯诈唬';}
function weightedEquity(hero:Card[],board:Card[],range:WeightedCombo[]){let value=0;for(const c of range){const result=exactEquity([hero,c.cards],board);value+=result.equity[0]*c.weight;}return value;}
export function analyzeDecision(input:DecisionAnalysisInput):DecisionFacts{
  const equity=weightedEquity(input.hero,input.board,input.range),requiredEquity=input.toCall?potOdds(input.toCall,input.pot):0;const representative=[...input.range].sort((a,b)=>b.weight-a.weight).slice(0,8);let outs:{clean:Card[];dirty:Card[]}={clean:[],dirty:[]};if(input.board.length<5&&representative.length){const results=representative.map(x=>cleanOuts(input.hero,input.board,[x.cards]));const candidates:Card[]=[...new Set<Card>(results.flatMap(x=>[...x.clean,...x.dirty]))];outs={clean:candidates.filter(c=>results.every(x=>x.clean.includes(c))),dirty:candidates.filter(c=>results.some(x=>x.dirty.includes(c)))};}const drawPotential=Math.min(.5,outs.clean.length*(input.board.length===3?.02:.04));
  const fold:Alternative={kind:'fold',action:'弃牌',amount:0,ev:0,risk:0,intent:'控池',equity,foldEquity:1};const callEv=equity*(input.pot+input.toCall)-input.toCall;const call:Alternative={kind:'call',action:input.toCall?`跟注 ${input.toCall}`:'过牌',amount:input.toCall,ev:callEv,risk:input.toCall,intent:classifyIntent(equity,.08,drawPotential),equity,foldEquity:0};
  const alternatives=[fold,call];for(const fraction of [.5,.75,1]){const amount=Math.min(input.stack,Math.max(input.toCall+2,Math.round(input.pot*fraction)));const strengthFold=Math.max(.08,Math.min(.58,.35-.18*equity+.16*fraction));const behindPenalty=input.playersBehind*.06;const foldEquity=Math.max(.02,strengthFold-behindPenalty);const finalPot=input.pot+amount*2;const ev=foldEquity*input.pot+(1-foldEquity)*(equity*finalPot-amount)-behindPenalty*amount;alternatives.push({kind:'raise',action:`加注到 ${amount}`,amount,ev,risk:amount,intent:classifyIntent(equity,foldEquity,drawPotential),equity,foldEquity});}
  const recommended=[...alternatives].sort((a,b)=>b.ev-a.ev)[0];return{equity,requiredEquity,outs,alternatives,recommended,risk:{playersBehind:input.playersBehind,effectiveStack:input.stack,spr:input.stack/input.pot},assumptions:['未知底牌按当前组合权重枚举','普通朋友局跟注偏宽、诈唬偏少','身后玩家按额外继续风险折减加注 EV','未计未来街复杂策略与隐含赔率']};
}
